#!/usr/bin/env bash

#npm install --package-lock-only --save @arbennett/base16-gruvbox-dark
#npm install --package-lock-only --save-dev @jupyterlab/builder

npm update --package-lock-only
npm audit fix --package-lock-only

#rm package-lock.json
#node2nix --development

node2nix --development --lock package-lock.json
